exports.up = (knex, Promise) => {
    return knex.schema.createTable('classic_lengthened', (table) => {
    table.increments('id').primary()
    table.string('name_after_lengthened')
    table.string('lengthened_service_yrs')
    table.string('lengthened_operator')
    table.integer('lengthened_reg_port')
    table.string('lengthened_cost')
    table.string('lengthened_passengers')
    table.string('lengthened_crew')
    table.integer('lengthened_gt')
    table.string('lengthened_length')
    table.integer('lengthened_beam')
    table.string('lengthened_draft')
    table.string('lengthened_deadweight')    
    table.string('lengthened_lightship')
    table.integer('lengthened_displacement')
    table.integer('lengthened_funnel_hgt')
    table.string('lengthened_speed')
    table.string('lengthened_deadweight')
    table.string('lengthened_lightship') 
    table.string('lengthened_displacement') 
    table.string('lengthened_power')
    table.string('lengthened_power_rpm')
    table.string('lengthened_fuel_capacity')
    table.string('lengthened_fuel_consumption')
    table.string('lengthened_propellors')
    table.string('lengthened_propellor_size')
    table.string('lengthened_rudder_size')
    table.integer('lengthened_decks')
    table.integer('lengthened_passenger_decks') 
    table.string('lengthened_bridge_height')
    table.string('lengthened_bridge_water')
    table.string('lengthened_shelter_deck')
    table.string('lengthened_bow_bridge')
    table.string('lengthened_bow_height')
  })
};  

exports.down = (knex, Promise) => {
    return knex.schema.dropTable('classic_lengthened')
};
