exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries 
  // await knex('table_name').del()
  // Delete all existing entries is being taken care of in 00_clean.js seeds file
  return knex('classic_lengthened').insert([
    {id: 1, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 2, name_after_lengthened: '',
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 3, name_after_lengthened: '',
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 4, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 5, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 6, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 7, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 8, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 9, name_after_lengthened: 'Song of Norway (1978 to 1997)', 
    lengthened_service_yrs: '1978 to 2013', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '1196', lengthened_crew: '423', lengthened_gt: '22945',  lengthened_length: '194.32 m (637 feet 6.4 inches)',
    lengthened_beam: '24 m (78 feet 8.8 inches)', lengthened_draft: '7.2 m maybe', lengthened_deadweight: '4,525 Tonnes', 
    lengthened_lightship: '', lengthened_displacement: '',  lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: 'Same as built',
    lengthened_power_rpm: 'Same as built', lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},

    {id: 10, name_after_lengthened: 'Royal Viking Sky (1982 to 1991)',
    lengthened_service_yrs: '1982 to 2021', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '900', lengthened_crew: '320', lengthened_gt: '28372', 
    lengthened_length: '205.47 m (674 feet 1.37 inches)', lengthened_beam: '25.19 m (82 feet 7.73 inches)',
    lengthened_draft: '7.55 m (24 feet 9.25 inches)', lengthened_deadweight: '5956 Tonnes',
    lengthened_lightship: '15760 Tonnes', lengthened_displacement: '21716 Tonnes', lengthened_funnel_hgt: '',
    lengthened_speed: '22 knots (41 km/ hr or 25 mph)', lengthened_power: '14,000 kW (18,774.29 Horsepower)',
    lengthened_power_rpm: '', lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', 
    lengthened_propellors: '', lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',
    lengthened_decks: '', lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},


    {id: 11, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''},


    {id: 12, name_after_lengthened: '', 
    lengthened_service_yrs: '', lengthened_operator: '', lengthened_reg_port: '', lengthened_cost: '',
    lengthened_passengers: '', lengthened_crew: '', lengthened_gt: '',  lengthened_length: '', lengthened_beam: '',
    lengthened_draft: '', lengthened_deadweight: '', lengthened_lightship: '', lengthened_displacement: '', 
    lengthened_funnel_hgt: '',lengthened_speed: '', lengthened_power: '',lengthened_power_rpm: '', 
    lengthened_fuel_capacity: '', lengthened_fuel_consumption: '', lengthened_propellors: '', 
    lengthened_propellor_size: '', lengthened_rudder: '', lengthened_rudder_size:'',lengthened_decks: '', 
    lengthened_passenger_decks: '', lengthened_bridge_height: '', lengthened_bridge_water: '',
    lengthened_shelter_deck: '', lengthened_bow_bridge: '', lengthened_bow_height: ''}    

  ]);
};